version: 2

jobs:
  build:
    working_directory: ~/pymox
    docker:
      - image: circleci/python:2.7.11
    environment:
      CODECOV_TOKEN: 07a918bb-31b1-49fc-b4d9-55db4858a3fd
    steps:
      - checkout
      - run: python mox_test.py
      # - run: codecov --token=$CODECOV_TOKEN
