version: 2

jobs:
  build:
    working_directory: ~/pymox
    docker:
      - image: circleci/python
    environment:
      CODECOV_TOKEN: 07a918bb-31b1-49fc-b4d9-55db4858a3fd
    steps:
      - checkout
      - run:
          command: |
            sudo pip install codecov==1.6.3
            sudo pip install tox tox-pyenv
      - run:
          command: |
            curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
            echo 'export PATH="/home/circleci/.pyenv/bin:$PATH"' >>~/.bash_profile
            echo 'eval "$(pyenv init -)"' >>~/.bash_profile
            echo 'eval "$(pyenv virtualenv-init -)"' >>~/.bash_profile
            source ~/.bash_profile
            pyenv install 2.7.13
            pyenv install 3.3.6
            pyenv install 3.4.6
            pyenv install 3.5.3
            pyenv install 3.6.2
            pyenv local 2.7.13 3.3.6 3.4.6 3.5.3 3.6.2
      - run:
          command: |
            source ~/.bash_profile
            tox
      - run: codecov --token=$CODECOV_TOKEN
